### PR TITLE
Update Envoy to v1.9.0

### PR DESCRIPTION
**Pull request by stefanprodan**
Fix: #27 

Test infra: https://github.com/stefanprodan/appmesh-eks

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by mhausenblas** [comment]
Very cool, thanks @stefanprodan … I'm also depending on this for the X-Ray walkthrough I'm working on in the [examples repo](https://github.com/aws/aws-app-mesh-examples/tree/master/walkthroughs/eks).

**Comment by jqmichael** [comment]
Looks good. Should we also update this line https://github.com/aws/aws-app-mesh-inject/blob/master/cmd/app-mesh-inject/main.go#L55 ?

**Comment by stefanprodan** [comment]
I'll change it in main.go also but I don't think we should be doing this on the long run as in we don't have to release a new webhook image if only the sidecar image tag changes.

**Comment by jqmichael** [comment]
> I'll change it in main.go also but I don't think we should be doing this on the long run as in we don't have to release a new webhook image if only the sidecar image tag changes.

If updating webhook image is trivial (say we have a CI/CD system in place), why not? :)

**Pull request merged**
