### PR TITLE
cut v0.5.0 release

### PR DESCRIPTION
**Pull request by lavignes**
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by M00nF1sh** [comment]
hi, would you help change to v0.5.0, the next version we plan to cut is v0.5.0 :D

**Comment by lavignes** [comment]
No problem! I was just suggested to make this v0.4.1.

**Comment by jaypipes** [comment]
@M00nF1sh are we waiting on any other code changes for 0.5.0? If not, I'll merge this and either you or I can cut the git tag.

**Comment by lavignes** [comment]
@M00nF1sh I think we should cut this release ASAP. Customers seem to also still be running into the EKS on Fargate issues and it is also pending this release.

**Comment by M00nF1sh** [comment]
@jaypipes we are waiting for a controller change and it's just merged.
merging this.

**Pull request merged**
