### PR TITLE
Remove --no-cache from docker build

### PR DESCRIPTION
**Pull request by nckturner**
*Description of changes:*
Enable build caching to speed up docker builds.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by jqmichael** [comment]
Our docker run command doesn't seem to changes across builds. 

https://github.com/aws/aws-app-mesh-inject/blob/master/Dockerfile

We might need to add hash code of each commit to the Docker file so that we can safely take the advantage of using docker cache. 

> However, that cache is used pretty aggressively and may cause issues when you want the updated output of a RUN command to make it into the new container. As it stands, unless the RUN command *itself* changes (and thus invalidates Docker’s on-host cache), Docker will reuse the previous results from cache. This is clearly disadvantageous when the RUN command is a source code checkout, for example a git clone that is RUN as the initial step of a project’s build.

```
To get a fresh clone while still taking advantage of the cache, the engineer could place the source control operations into the last RUN that is listed in the Dockerfile.

But in order to make this a unique command, thus ensuring it gets run each time, the engineer could wrap the Docker build in another script that generates a uniquely-numbered mini-script for the clone operation.

This step would insert the invocation of that script into the Dockerfile that is generated on-the-fly just prior to build time, such that for the operation that must be run every time – the clone – its RUN statement is indeed unique, i.e.

RUN /bin/sh /foo-1234567abc.sh
```

https://thenewstack.io/understanding-the-docker-cache-for-faster-builds/

**Comment by nckturner** [comment]
I think you have valid points, but I think we can trust the `RUN go mod download` because the full sequence of events is: 

```
COPY go.mod .
COPY go.sum .

RUN go mod download
```

which means we will re-run go mod download if and only if anything in go.mod or go.sum change.

**Comment by nckturner** [comment]
The relevant points are here:

> For the ADD and COPY instructions, the contents of the file(s) in the image are examined and a checksum is calculated for each file. The last-modified and last-accessed times of the file(s) are not considered in these checksums. During the cache lookup, the checksum is compared against the checksum in the existing images. If anything has changed in the file(s), such as the contents and metadata, then the cache is invalidated.

> Once the cache is invalidated, all subsequent Dockerfile commands generate new images and the cache is not used.

https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#leverage-build-cache

**Comment by jqmichael** [comment]
Thanks for pointing to the caching doc! 
Since we always **COPY** `go.mod` and the final binary file. Cache will be invalidated if any of them change. Should be safe to use cache then.  
```
COPY go.mod .
COPY go.sum .
COPY --from=build-env /go/src/github.com/aws/aws-app-mesh-inject/appmeshinject .
```

**Pull request merged**
