### PR TITLE
Change namespace to appmesh-system

### PR DESCRIPTION
**Pull request by jasonrichardsmith**
*Issue #, if available:*

*Description of changes:*
This changes all references to namespace to appmesh-system

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by stefanprodan** [comment]
I would also change the name to match the Helm installers e.g. `appmesh-inject` instead of `aws-app-mesh-inject`, also drop `-sa` and other suffixes. Please see my suggestions on #90

**Comment by jasonrichardsmith** [comment]
Sorry @stefanprodan I missed those.  That is what I get for reading git comments from my phone.

**Comment by jasonrichardsmith** [comment]
This has been untested.  Name changed to [WIP]

**Comment by jasonrichardsmith** [comment]
I tested kustomize and cli install and they both worked.

**Comment by nckturner** [comment]
Agreed @jaypipes, should we just add a note in the README or release notes?

**Comment by jaypipes** [comment]
> Agreed @jaypipes, should we just add a note in the README or release notes?

I think at a minimum a note in the README would be necessary, yeah.

**Comment by jasonrichardsmith** [comment]
@nckturner @jaypipes I did add this to the README
### Warning
To align our helm repository and this repository we have changed the namespace to appmesh-system and resource names to appmesh-inject. 

Do you want something more in depth on upgrade procedures?

**Comment by nckturner** [comment]
Actually, everyone has approved, I'll just merge now :fearful:

**Pull request merged**
